# Generated by Django 3.1.3 on 2023-03-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_customers'),
        ('transaction', '0001_initial'),
        ('customer', '0002_auto_20230311_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='accounts',
            field=models.ManyToManyField(through='transaction.Transaction', to='account.Account'),
        ),
    ]
