# Generated by Django 3.1.3 on 2023-03-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bicswift', models.CharField(max_length=18)),
                ('address', models.TextField()),
                ('total_assets', models.FloatField()),
                ('total_equity', models.FloatField()),
            ],
        ),
    ]
