# Generated by Django 3.1.3 on 2023-03-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_branch_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='total_assets',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='total_equity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
