# Generated by Django 3.1.3 on 2023-03-12 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
        ('branch', '0002_remove_branch_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bank.bank'),
            preserve_default=False,
        ),
    ]
