USE CloudGaming
GO

--SET DEADLOCK_PRIORITY HIGH --solution

SELECT * FROM Users
SELECT * FROM Games

BEGIN TRAN
UPDATE Users SET Age=47 WHERE Uid = 91
WAITFOR DELAY '00:00:10'
UPDATE Games SET Rating=2 WHERE Gid=36
COMMIT TRAN