USE CloudGaming
GO

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
--SET TRANSACTION ISOLATION LEVEL READ COMMITTED --solution
BEGIN TRANSACTION
SELECT * FROM Users
WAITFOR DELAY '00:00:15'
SELECT * FROM Users
COMMIT TRAN