USE CloudGaming
GO

SET TRANSACTION ISOLATION LEVEL READ COMMITTED
--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ -- solution
BEGIN TRAN
SELECT * FROM Users
WAITFOR DELAY '00:00:05'
SELECT * FROM Users
COMMIT TRAN