USE CloudGaming
GO

--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE -- solution
BEGIN TRAN
SELECT * FROM Users
WAITFOR DELAY '00:00:05'
SELECT * FROM Users
COMMIT TRAN