# Generated by Django 3.1.3 on 2023-03-19 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_auto_20230313_0631'),
        ('account', '0002_remove_account_aid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='branch',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.branch'),
        ),
    ]
