# Generated by Django 3.1.3 on 2023-03-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
        ('customer', '0002_auto_20230311_2313'),
        ('account', '0003_account_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='customers',
            field=models.ManyToManyField(through='transaction.Transaction', to='customer.Customer'),
        ),
    ]
