# Generated by Django 3.1.3 on 2023-03-04 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='aid',
        ),
    ]
