version: '3'
services:
  mariadb:
    image: bitnami/mariadb:10.3
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_testlink
      - MARIADB_DATABASE=bitnami_testlink
    ports:
      - '3306:3306'
    volumes:
      - './mariadb_data:/bitnami/mariadb'
  testlink:
    build:
      context: .
      dockerfile: testlink.Dockerfile
    ports:
      - '8090:8090'
      - '8443:8443'
    environment:
      - TESTLINK_DATABASE_HOST=mariadb
      - TESTLINK_DATABASE_PORT_NUMBER=3306
      - TESTLINK_DATABASE_USER=bn_testlink
      - TESTLINK_DATABASE_NAME=bitnami_testlink
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - TESTLINK_USERNAME=student
      - TESTLINK_PASSWORD=student
      - APACHE_HTTP_PORT_NUMBER=8090
    volumes:
      - './testlink_data:/bitnami/testlink'
    depends_on:
      - mariadb
    
  jenkins:
    build:
      context: .
      dockerfile: jenkins-maven.Dockerfile
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_data:/var/jenkins_home
    
# API '1a19146efb3cc122757f1f2b3d628cd0'
