# Generated by Django 3.1.3 on 2023-03-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='address',
        ),
        migrations.AddField(
            model_name='bank',
            name='ceo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='headquarters',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
