# Generated by Django 4.1.7 on 2023-04-02 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0002_auto_20230319_1025"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankQuery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_branches", models.IntegerField()),
                (
                    "bank",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="bank.bank"
                    ),
                ),
            ],
        ),
    ]
